version: '3.4'

services:
  fpm-81:
    build:
      context: .
      target: base
      dockerfile: dockerfiles/Dockerfile-fpm-8_1
    volumes:
      - ./tests:/var/www/html
    entrypoint: [ "./entrypoint-tests" ]
    command: [ "php", "test.php" ]

  composer-2:
    build:
      context: .
      target: composer
      dockerfile: dockerfiles/Dockerfile-fpm-8_1
    volumes:
      - ./tests:/var/www/html
    entrypoint: [ "./entrypoint-tests" ]
    command: [ "php", "test.php" ]
