#!/usr/bin/env bash

# Set default value to false if the environment variable is not set
ENABLE_XDEBUG=${ENABLE_XDEBUG:-"false"}
cp /usr/local/etc/php/conf.d/general.ini /usr/local/etc/dev-extension/general.ini.back
if [ ! "prod" == "$APP_ENV" ] && [ ! "staging" == "$APP_ENV" ]; then
  if [ -e /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini ]; then
      rm -f /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
  fi
  echo ">> [INFO] Opcache is disabled"

  if [ "$ENABLE_XDEBUG" = "true" ]; then
    # Enable xdebug
    rm -f /usr/local/etc/php/conf.d/general.ini
    cat /usr/local/etc/dev-extension/general.ini.back > /usr/local/etc/php/conf.d/general.ini
    cat /usr/local/etc/dev-extension/docker-php-ext-xdebug.ini >> /usr/local/etc/php/conf.d/general.ini

    echo ">> [INFO] XDebug is enabled ⚠️"
  else
      rm -f /usr/local/etc/php/conf.d/general.ini
      cp /usr/local/etc/dev-extension/general.ini.back /usr/local/etc/php/conf.d/general.ini
      echo ">> [INFO] XDebug is disabled ✅"
  fi
else
  ln -sf /usr/local/etc/dev-extension/docker-php-ext-opcache.ini /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
  echo ">> [INFO] Opcache is enabled ✅"
fi
