name: Build and push image

on:
  push:
jobs:
  test:
    name: Test the images 🧪
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker-compose build
      - run: docker-compose run -e ENABLE_XDEBUG=false fpm-82 php test.php
        continue-on-error: false
      - run: docker-compose run -e ENABLE_XDEBUG=false composer-2-82 php test.php
        continue-on-error: false

  push_to_registry:
    name: Push Docker image to Docker Hub 🔼
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push composer image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./dockerfiles/Dockerfile-fpm-8_2
          target: composer-81
          push: true
          tags: alexromer0/php:composer-82

      - name: Build and push base image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./dockerfiles/Dockerfile-fpm-8_2
          target: base
          push: true
          tags: alexromer0/php:fpm-82
