name: Build and push image

on:
  push:
    branches:
      - *
    tags:
      - *
jobs:
  test:
    name: Test the images 🧪
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull image
        run: docker-compose pull
      - run: docker-compose up

  push_to_registry:
    name: Push Docker image to Docker Hub 🔼
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push composer image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./dockerfiles/Dockerfile-fpm-8_1
          target: composer
          push: true
          tags: fpm-81

      - name: Build and push base image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./dockerfiles/Dockerfile-fpm-8_1
          target: composer
          push: true
          tags: composer-81
